development:
  adapter: sqlite3
  database: db/movember_development.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  database: movember_development
  pool: 5
  username: felixmohnert
  password: