development:
  adapter: postgresql
  encoding: unicode
  database: movember_development
  pool: 5
  username: felixmohnert
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: movember_development
  pool: 5
  username: felixmohnert
  password: